name: Build Game

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows, HTML5, MacOS]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Infinity-Engine-Godot
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: Infinity-Engine-Godot
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
